Fix missing closing tag.
ruricolist/spinneret pull request #71
Opened 2023-01-19 10:43 UTC by aadcg

2023-01-19 13:38 UTC, aadcg commented
I've now realized that non closed tags generate valid HTML.

Therefore I believe I must close this PR.

Unrelated: does spinneret provide a way to force closing tags?  Thanks.

2023-01-19 13:45 UTC, ruricolist commented
That can be done with *html-style*.

2023-01-19 18:25 UTC, aadcg commented
Thanks @ruricolist!

See the changes that I propose, in light of the insights.

2023-01-19 22:27 UTC, ruricolist requested changes

2023-01-19 22:27 UTC, ruricolist commented on README.md
> +Notice that bounding `*html-style*` to `:tree` ensures that all tags are
"bounding" should be "binding"

2023-01-26 08:23 UTC, aadcg commented on README.md
> +Notice that bounding `*html-style*` to `:tree` ensures that all tags are
I've fixed it, thanks.

2023-01-26 22:44 UTC, merged

2023-01-26 22:44 UTC, ruricolist approved these changes